name: CI

on: [push, pull_request]

jobs:
  CI:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.11.5"
            pytorch-version: "2.0.1"
            pylint-version: "2.17.7"
          - python-version: "3.11.5"
            pytorch-version: "2.0.1"
            pylint-version: "3.0.2"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip --version
          python -m pip install pylint==${{ matrix.pylint-version }}
          python -m pip install torch==${{ matrix.pytorch-version }}+cpu --index-url https://download.pytorch.org/whl/cpu
      - name: Run pylint
        run: |
          which python
          python -c "import sys; print(sys.version)"
          python -c "import torch; print(torch.__version__)"
          python -m pylint --version
          python -m pylint main.py "--generated-member=torch.*,torch.linalg.*"
        working-directory: ${{ github.workspace }}
